Import dynamic zones
Baboo7/strapi-plugin-import-export-entries pull request #97
Opened 2023-03-02 10:33 UTC by mitenka

When import repeatable components into content type's dynamic zones, the `component_type` column sets to `null`, which makes duplicates after dynamic zone editing. This PR (hopefully) fixes it.

2023-04-02 19:19 UTC, Kyle772 commented
I tried to implement this PR in my project but I'm getting the same behavior. All but 2 of my component types are null. On the specific item I'm importing into there are exactly two different component types available. Something is forcing the column to only have unique values despite this not being the case in my other strapi tables.

Are there any work arounds? I have over 300 entities all with repeatable components :/

2023-04-03 16:04 UTC, mitenka commented
Hey @Kyle772. The PR should work not only for dynamic zones, but any repeatable components. In case your records already hold `NULL` values for `component_type`, this PR won't fix already corrupted data. It's prevents setting `component_type` to `NULL` for newly imported data. I fix corrupted data manually. Let me know if it helps

2023-04-10 11:19 UTC, Baboo7 requested changes

2023-04-10 11:19 UTC, Baboo7 commented on server/services/import/import-v2.js
> +    const attributeNames = getModelAttributes(slug, {
These changes should not appear since it's just linting. Configure your linter properly to rollback changes

2023-04-10 18:54 UTC, Baboo7 commented
Otherwise the PR looks good to me 👍

2023-04-11 12:28 UTC, Baboo7 commented
I'll modify your PR when I have time ;)

About ids differing in different environment, I've been working on it this weekend to map ids from the file to ids in database when elements are created or updated. I'll merge our work together.

2023-04-22 17:18 UTC, merged

2023-11-21 04:08 UTC, fabwoofer commented
Hey guys, thanks for the great work here. The fix seems to be working for manual import/export (through the GUI) but not for the export service. Are there any differences between the 2 export types? I have compared the output json files and definitely see differences, although I am applying the same settings.

2023-11-21 23:52 UTC, fabwoofer commented
> > The fix seems to be working for manual import/export (through the GUI) but not for the export service. Are there any differences between the 2 export types?
> 
> Do you mean [data transfer](https://docs.strapi.io/dev-docs/data-management/transfer)? If so, yes, it's completely different approach

No, I mean the `Content API` as described in the documentation here https://market.strapi.io/plugins/strapi-plugin-import-export-entries

I have a script that exports data from one environment using the export function of the `Content API` and then import it through the import function of the same api in a different environment. So my question is if the `Content API` export differs from the manual export through the GUI since the exported JSON file is different

2023-11-22 06:45 UTC, fabwoofer commented
Never mind, I did some digging and found out that I have to pass `json-v2` for the `format` parameter. Just seems like the documentation needs some updating. Thanks for the quick reply though.